swagger: "2.0"
info:
  version: 1.0.0
  title: Flio API
host: localhost
basePath: "/v1"
schemes:
- https
- http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

paths:
    $ref: ./services/paths.yaml

definitions:
    $ref: ./services/definitions.yaml
