swagger: "2.0"
info:
  version: 1.0.0
  title: Flio API
host: localhost:5000
basePath: "/api/v1"
schemes:
- https
- http
securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header

paths:
    $ref: ./services/paths.yaml

definitions:
    $ref: ./services/definitions.yaml
